language: c

cache:
  apt: true
  directories:
    - mk/.cache

env:
  global:
    - AUTOQEMU_NICS=''
  matrix:
    - TEMPLATE=arm/qemu
    - TEMPLATE=arm/stm32_f4
    - TEMPLATE=x86/qemu
    - TEMPLATE=x86/test/lang

before_install:
  - travis_retry sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - travis_retry sudo apt-get update -qq

# TODO make it template-specific
install:
  - travis_retry sudo apt-get install -qq gcc-arm-embedded
  - travis_retry sudo apt-get install -qq gcc-multilib
  - travis_retry sudo apt-get install -qq u-boot-tools
  - travis_retry sudo apt-get install -qq qemu qemu-system

before_script:
  - unset CC
  - export CC
  - make confload-"$TEMPLATE"
  - sed -ie '/eth0\|http/d' conf/start_script.inc  # FIXME
  - make buildgen  # Make as much as possible before the actual build step.

script:
  - make && ./scripts/continuous/run.sh "$TEMPLATE"

